platform :ios, '9.0'

use_frameworks!

target 'AdaptationKit_Example' do
  pod 'AdaptationKit', :path => '../'

  target 'AdaptationKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
